#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomPage.HangfireExtensions.ManagementPage
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
    using CustomPage.HangfireExtensions.ManagementPage;
    
    #line default
    #line hidden
    
    #line 3 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 4 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 5 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
    using Newtonsoft.Json;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class Management : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");






WriteLiteral("\r\n");


            
            #line 8 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
  
    Layout = new LayoutPage("Management");

    var tables = new List<Func<RazorPage, MenuItem>>();

    foreach (var table in AvailableTables)
    {
        var segment = $"{ManagementPageExtensions.UrlPath}/{table.Name}";
        tables.Add(page => new MenuItem(table.Name, page.Url.To(segment))
                {
                    Active = page.RequestPath.StartsWith(segment)
                });
    }

    var data = ReadData(CurrentTable);


            
            #line default
            #line hidden
WriteLiteral("<link rel=\"stylesheet\" type=\"text/css\" href=\"");


            
            #line 24 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
                                         Write($"{ManagementPageExtensions.UrlPath[1..]}Resources/css/style.css");

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n<script src=\"");


            
            #line 25 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
         Write($"{ManagementPageExtensions.UrlPath[1..]}Resources/js/vue.global.js");

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n<script src=\"");


            
            #line 26 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
         Write($"{ManagementPageExtensions.UrlPath[1..]}Resources/js/axios.min.js");

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n<script src=\"");


            
            #line 27 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
         Write($"{ManagementPageExtensions.UrlPath[1..]}Resources/js/app.js");

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n<div class=\"row\">\r\n    <div class=\"col-md-3\">\r\n        ");


            
            #line 30 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
   Write(Html.SidebarMenu(tables));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div class=\"col-md-9\">\r\n        <h1 class=\"page-header\">");


            
            #line 33 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
                            Write(CurrentTable.Name ?? "Management");

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n");


            
            #line 34 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
         if (tables.Count == 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"alert alert-warning\">\r\n                No tables configur" +
"ed\r\n            </div>\r\n");


            
            #line 39 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <div id=\"app\" data-rows=\"");


            
            #line 42 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
                                Write(JsonConvert.SerializeObject(data.Select(x=>JsonConvert.SerializeObject(x))));

            
            #line default
            #line hidden
WriteLiteral("\" data-save-url=\"");


            
            #line 42 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
                                                                                                                              Write($"{ManagementPageExtensions.UrlPath[1..]}Actions/Save");

            
            #line default
            #line hidden
WriteLiteral("\" data-table-name=\"");


            
            #line 42 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
                                                                                                                                                                                                         Write(CurrentTable.Name);

            
            #line default
            #line hidden
WriteLiteral(@""" class=""js-jobs-list"">
                <div class=""table-responsive"">
                    <table class=""table"">
                        <thead>
                        <tr>
                            <th class=""min-width"">№</th>
                            <th>JSON</th>
                            <th style=""width: 5%""></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr v-for=""(row, index) in rows"" class=""js-jobs-list-row"">
                            <td>{{index + 1}}</td>
                            <td class=""word-break"">
                                <input type=""text"" v-model=""rows[index]""/>
                            </td>
                            <td>
                                <button role=""button"" class=""management-button danger"" ");


WriteLiteral(@"@click=""remove(index)"">Remove</button>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    <div class=""buttons"">
                        <button role=""button"" ");


WriteLiteral("@click=\"add\" class=\"management-button primary\">Add</button>\r\n                    " +
"    <button role=\"button\" ");


WriteLiteral("@click=\"save\" class=\"management-button success\">Save</button>\r\n                  " +
"  </div>\r\n                </div>\r\n            </div>\r\n");


            
            #line 70 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
